const modalProduct = [
  {
    id: 0,
    title: "Monaco Grand Prix Poster",
    visibility: "",
    price: 59.99,
    instock: 23,
    category: "tracks",
    alt: "poster of Monaco Grand Prix with scenic background",
    img: "img/cars/tracks/monaco1.jpg",
    brand: "PosterCo",
    code: "101",
    points: "150",
    instock: "15",
  },
  {
    id: 1,
    title: "Silverstone Circuit Poster",
    visibility: "",
    price: 49.99,
    instock: 18,
    category: "tracks",
    alt: "artistic poster of Silverstone circuit",
    img: "img/cars/tracks/silverstone1.jpg",
    brand: "TrackArt",
    code: "102",
    points: "180",
    instock: "12",
  },
  {
    id: 2,
    title: "Spa-Francorchamps Poster",
    visibility: "",
    price: 39.99,
    instock: 20,
    category: "tracks",
    alt: "poster featuring Spa-Francorchamps circuit layout",
    img: "img/cars/tracks/spa1.jpg",
    brand: "PosterLab",
    code: "103",
    points: "140",
    instock: "20",
  },
  {
    id: 3,
    title: "Red Bull Racing Poster",
    visibility: "",
    price: 69.99,
    instock: 10,
    category: "teams",
    alt: "poster showcasing Red Bull Racing team logo and car",
    img: "img/cars/teams/redbull1.jpg",
    brand: "TeamPrints",
    code: "201",
    points: "200",
    instock: "10",
  },
  {
    id: 4,
    title: "Ferrari Legacy Poster",
    visibility: "",
    price: 89.99,
    instock: 8,
    category: "teams",
    alt: "poster celebrating Ferrari's history in F1",
    img: "img/cars/teams/ferrari1.jpg",
    brand: "ScuderiaArt",
    code: "202",
    points: "220",
    instock: "8",
  },
  {
    id: 5,
    title: "Mercedes-AMG Team Poster",
    visibility: "",
    price: 79.99,
    instock: 14,
    category: "teams",
    alt: "poster highlighting Mercedes-AMG Petronas team",
    img: "img/cars/teams/mercedes1.jpg",
    brand: "PosterHub",
    code: "203",
    points: "210",
    instock: "14",
  },
  {
    id: 6,
    title: "McLaren Speed Poster",
    visibility: "",
    price: 59.99,
    instock: 20,
    category: "teams",
    alt: "poster showcasing McLaren team's car and logo",
    img: "img/cars/teams/mclaren1.jpg",
    brand: "SpeedArt",
    code: "204",
    points: "180",
    instock: "20",
  },
  {
    id: 7,
    title: "Alpine F1 Poster",
    visibility: "",
    price: 49.99,
    instock: 18,
    category: "teams",
    alt: "poster featuring Alpine team's car in action",
    img: "img/cars/teams/alpine1.jpg",
    brand: "F1Posters",
    code: "205",
    points: "170",
    instock: "18",
  },
  {
    id: 8,
    title: "Williams Legacy Poster",
    visibility: "",
    price: 39.99,
    instock: 16,
    category: "teams",
    alt: "poster highlighting Williams Racing history",
    img: "img/cars/teams/williams1.jpg",
    brand: "PosterLegends",
    code: "206",
    points: "150",
    instock: "16",
  },
  {
    id: 9,
    title: "Lewis Hamilton Victory Poster",
    visibility: "cars__hide",
    price: 99.99,
    instock: 5,
    category: "drivers",
    alt: "poster celebrating Lewis Hamilton's championship victories",
    img: "img/cars/drivers/hamilton1.jpg",
    brand: "DriverPosters",
    code: "301",
    points: "250",
    instock: "5",
  },
  {
    id: 10,
    title: "Max Verstappen Champion Poster",
    visibility: "cars__hide",
    price: 89.99,
    instock: 6,
    category: "drivers",
    alt: "poster featuring Max Verstappen's car and championship win",
    img: "img/cars/drivers/verstappen1.jpg",
    brand: "PosterKings",
    code: "302",
    points: "230",
    instock: "6",
  },
  {
    id: 11,
    title: "Ayrton Senna Tribute Poster",
    visibility: "cars__hide",
    price: 129.99,
    instock: 3,
    category: "drivers",
    alt: "poster honoring Ayrton Senna's legacy",
    img: "img/cars/drivers/senna1.jpg",
    brand: "LegendaryPrints",
    code: "303",
    points: "300",
    instock: "3",
  },
  {
    id: 12,
    title: "Michael Schumacher Dominance Poster",
    visibility: "cars__hide",
    price: 149.99,
    instock: 4,
    category: "drivers",
    alt: "poster showcasing Michael Schumacher's F1 career highlights",
    img: "img/cars/drivers/schumacher1.jpg",
    brand: "PosterCo",
    code: "304",
    points: "350",
    instock: "4",
  },
  {
    id: 13,
    title: "Sebastian Vettel Legacy Poster",
    visibility: "cars__hide",
    price: 109.99,
    instock: 7,
    category: "drivers",
    alt: "poster celebrating Sebastian Vettel's career",
    img: "img/cars/drivers/vettel1.jpg",
    brand: "F1Posters",
    code: "305",
    points: "280",
    instock: "7",
  },
  {
    id: 14,
    title: "Fernando Alonso Speed Poster",
    visibility: "cars__hide",
    price: 119.99,
    instock: 6,
    category: "drivers",
    alt: "poster featuring Fernando Alonso in action",
    img: "img/cars/drivers/alonso1.jpg",
    brand: "SpeedArt",
    code: "306",
    points: "300",
    instock: "6",
  },
  {
    id: 15,
    title: "Kimi Raikkonen Ice Poster",
    visibility: "cars__hide",
    price: 129.99,
    instock: 5,
    category: "drivers",
    alt: "poster highlighting Kimi Raikkonen's iconic moments",
    img: "img/cars/drivers/raikkonen1.jpg",
    brand: "LegendaryPrints",
    code: "307",
    points: "310",
    instock: "5",
  },
  {
    id: 16,
    title: "George Russell Rising Star Poster",
    visibility: "cars__hide",
    price: 79.99,
    instock: 9,
    category: "drivers",
    alt: "poster celebrating George Russell's rise in F1",
    img: "img/cars/drivers/russell1.jpg",
    brand: "PosterLab",
    code: "308",
    points: "200",
    instock: "9",
  },
];
